server:
  port: 8282
  context-path: /api
spring:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: false
  sleuth:
    sampler:
      percentage: 1
  application:
    name: some-service